### ISSUE TITLE
Field - Missing isHorizontal and no examples for isGrouped

### ISSUE THREAD

**Issue by steph4nc** [fibo/trunx#13]
I see the `is-horizontal` class is missing as a prop on https://github.com/fibo/trunx/blob/master/src/component/Field.tsx
https://bulma.io/documentation/form/input/

There is also no examples for isGrouped modifiers on Field on the storybook.

**Comment by fibo** [comment]
thanks for reporting it, you are helping me a lot. I will check it out.

**Comment by fibo** [comment]
I added missing props reported here and more stuff, available in version `v0.12.0` published on the registry just now.

Please note that I had to remove `label` prop in `Field` component.

Now the Input component story is completed. About the example required, honestly I am just adding examples copied from Bulma docs, adding only few examples related to extra stuff like icons or React stuff (for example Input has an additional **Ref** section) when I find that it is mandatory to add something. At this first phase of the project I am copying from Bulma until 100% coverage is completed.

However, adding more examples is a good idea, but honestly I would need some help to define it better.
