### ISSUE TITLE
Next.js example

### ISSUE THREAD

**Issue by fibo** [fibo/trunx#14]
See this example, do something similar with trunx components: https://github.com/jvarness/next-with-bulma

Actually I do not like storybook experience on mobile. It was great to start but trunx could now be used to create its own website, possibly really similar to bulma website (even carbon ads :)

I also submitted trunx storybook and pr was merged but the storybook examples are not on the storybook website, looks like they were removed.

**Comment by fibo** [comment]
see https://nextjs.org/learn/excel/static-html-export

**Comment by fibo** [comment]
see also https://mdxjs.com/getting-started/next

**Comment by jvarness** [comment]
Was looking around the internet for my repo and saw it was mentioned here :)

I'm glad you like the example! Are you thinking about possibly rewriting trunx's site using Next.js? I'm a fan myself :) this repository looks really cool and useful!

**Comment by fibo** [comment]
Hi @jvarness thank you for your example repo, it looks really inspiring for me. Yes I think that rewriting trunx's site using Next.js is a really interesting option.

By now I am using storybook and it is not that bad, but for sure when I finish to copy all Bulma documentation and will consider deploy first trunx major version, I will consider stealing code from your example repo.

**Comment by fibo** [comment]
@jvarness also using React Styleguidist ( issue here https://github.com/fibo/trunx/issues/19 ) looks promising.

**Comment by jvarness** [comment]
Interestingly enough, I found a project that's very similar to this one called [`re-bulma`](http://bokuweb.github.io/re-bulma/) that uses styleguidist in order to document all of it's components. I wonder if it would be worthwhile to combine the two projects?

**Comment by fibo** [comment]
@jvarness unfortunately the project is deprecated but it looks a good resource too see how to use *React Styleguidist*.

**Comment by fibo** [comment]
I tryed Next.js and I prefer to implement the documentation website with my usual workflow tools (i.e. a react build dome with browserify and the budo dev server).
