### ISSUE TITLE
100% TypeScript

### ISSUE THREAD

**Issue by fibo** [fibo/trunx#16]
Consider port the whole codebase to TypeScript.

Currently the storybook stories are written in JavaScript.

Furthermore, consider do not transpile at all, I mean to target only TypeScript users which could import somehow the .tsx files directly.

**Comment by ashnur** [comment]
I am fairly sure that an only typescript sourced trunx would not be something I would use. I use trunx now because I can ignore the typescript part. Again, I would happily use typescript if the type information would be available outside of development time - in a timely manner :D

**Comment by fibo** [comment]
Hi @ashnur 	thank you very much for your opinion.

Actually having the stories written in JavaScript is good. I already have a TypeScript project using trunx (the one linked in the readme) so I can check if something breaks there.
