### ISSUE TITLE
Custom element for components 

### ISSUE THREAD

**Issue by andreimc** [fibo/trunx#18]
Allowing us to specify what element should be rendered, there is a lot of advantage in this, similar to what react Bulma components is doing. I had some issues with using this with the navbar a elements within a elements

**Comment by fibo** [comment]
Hi @andreimc thank you for using trunx!

Do you refer to Bulma's `navbar-item` which could be an `a` element or, in case of a dropdown, a `div` element.

If yes I think it should be easy to fix the `Navbar.Item` component, which now renders always an `a`, to render a `div` element in case the `hasDropdown` boolean is true.

Is the issue you had related to the `Navbar.Item` behaviour I wrote above? Feel free to give any advice or suggestion you think it worth. Any feedback is welcome.

**Comment by fibo** [comment]
@andreimc I am working on that, thanks for the feedback.

**Comment by fibo** [comment]
navbar component should be fixed
