### ISSUE TITLE
className prop

### ISSUE THREAD

**Issue by fibo** [fibo/trunx#25]
add className prop to every component, in order to add a custom class

for example I added it in Icon, it can be useful to avoid a wrapper layer to add a class

**Comment by davetapley** [comment]
@fibo would you be open to a PR for this?

**Comment by fibo** [comment]
Hi, sure a PR would help. The idea is to use a similar approach as in the Icon component. Feel free to add className prop also only to the components you need.

**Comment by fibo** [comment]
@davetapley we have a PR [here](https://github.com/fibo/trunx/pull/26), regarding Nav component, thanks to @igaponov	.

**Comment by fibo** [comment]
@davetapley and @igaponov , your contributions are published on npm with version `0.33.0`

I will leave this issue open since the idea is to apply a className prop to all components

**Comment by fibo** [comment]
added `className` prop to almost all components https://github.com/fibo/trunx/commit/4c78e5cbcabf7070030a008b7609452e485f8bf6

**Comment by fibo** [comment]
just released `v0.34.0` where all components accept a `className` prop
