### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by ashnur** [fibo/trunx#3]
I am quite curious about where you want to lead this project @fibo and I think that some testing would help it make it very clear. Have you considered this angle before?

**Comment by fibo** [comment]
Hi @ashnur nice to hear about you and the fact you are cirious about it.

By now I am doing some manual functional tests on storybook to check that components are working but for sure I will add tests, 99,9% using jest.

Another next step you mau be interested is documenting how to customize bulma look&feel.

I am already doing it in my side project [go7.li](http://go7.li) and it is the main feature that motivated me to start this project.

It is a really common Sass setup, not yet documented but for sure I will customize style used in trunx storybook to provide a working example.

**Comment by ashnur** [comment]
Thanks for the elaborate answer.
Personally I use https://www.npmjs.com/package/tape whenever I can, but I guess the tooling is the least important detail here. 
May I ask what do you consider as a "working component"? Where I come from, the only good testing is generative testing with some kind of property based testing approach, and would be quite happy to contribute along these lines if it fits your goals. 
Beyond this, I have three main questions. How much of bulma you plan on implementing, do you want to create elaborate custom objects from bulma components in this repo, or just wrappers for existing classes and how long do you think you will be maintaining it after you will not need it? I don't expect anyone to put too much work in open source, as I barely have the time myself so I am a bit cautious to invest much time, on the other hand some nice react wrapper is in due for bulma, but despite many attempts I don't see any of them getting off the ground.

**Comment by fibo** [comment]
Good morning @ashnur and thank you for your interest.

Actually by "working components" I mean that my first goal is to, let me say, *clone* all the Bulma components, as well as the documentation. It makes sense for me to just add, by now, all the components that Bulma provides, and wrap all the CSS classes into React props adding few JS logic where it makes sense.

I am planning to use *trunx* also for other websites in the future, anyway even if I do not use a Bulma component yet, I think it is nice to complete the first goal. It could seem it is a lot of work, but, it is worth it considering that Bulma is so nice and configurable that will be for sure one of my first choices for future websites.

Then there are also Bulma extensions: if we can take benefit from *tree shaking* and hence if the build weights are not affected, it is worth to include them into *trunx* package.

I like a lot *tape*, and I also use it a lot. I know that it could sound weird for TDD fans but I prefer to add tests after all Bulma components are wrapped.

Let me add a last point, about **icons**: Bulma suggests Font Awesome, I am planning to create a wrapper of free icons, probably it will be in another project for reusability, and it will just wrap the `path` values from license free Font Awesome icons. The idea is to provide, probably with an additional package to install, a set of React components icons, ready to be used.

If you want to contribute in any way you are more than welcome, just let me know how I can help improving the interaction.

**Comment by fibo** [comment]
I added few features other than simply wrapping Bulma components, for example ClassicNavbar, and FontAwesome icons.
About testing, I am doing functional testing using storybook, plus TypeScript implementation it is by now the best way I found to test things.

**Comment by ashnur** [comment]
I am looking into using https://github.com/dubzzz/fast-check in the next couple of weeks, seems to be usable and with an active maintainer :)

**Comment by fibo** [comment]
@ashnur looks interesting, can you please provide an example test you think it could be added?

**Comment by ashnur** [comment]
I will try to make a PR over the weekend

**Comment by fibo** [comment]
Great, or if you prefer something lighter you can also write here some code, just to have an idea. Sorry, I never used that kind of testing, and I could understand better with an example but it looks really interesting.

**Comment by fibo** [comment]
few tests were added in test/ folder, some run with tape, others with tsc.
