### ISSUE TITLE
Release updated package

### ISSUE THREAD

**Issue by luhis** [fibo/trunx#30]
Hi there,

I just found your package, it looks like a great replacement for RBX.

I'm having issues due to the "./classnames" import in https://github.com/fibo/trunx/blob/main/src/component/renderElement.ts, but I can see that it has already been fixed.

Could you release an updated NPM package, so I can use the corrected code?

**Comment by fibo** [comment]
Hi @luhis thanks for the feedback, I thought it was already released, let me check...

**Comment by luhis** [comment]
i think it's still out of date,  you see this line: `var classnames_1 = require("./classnames");`, that's the problem I think.

In fact, check out the latest version that has been checked in to GitHub: https://github.com/fibo/trunx/blob/main/component/renderElement.js 
`var classNames_1 = require("./classNames");`
This is what we should have in the npm package.

**Comment by fibo** [comment]
Aaaaah I think I got it now, when I back home this evening I will try to fix it, thank you very much for reporting it (I am using a Mac and here it works, I guess that also on Windows it works and you are using Linux)

**Comment by fibo** [comment]
now it should be ok, I released `v0.37` (since few minor components where added)

https://unpkg.com/trunx@0.37.0/component/renderElement.js

**Comment by luhis** [comment]
Thanks, that has fixed it.  I'm running the build on Linux, and it is all fixed now.
