### ISSUE TITLE
Add auto value for margin and padding helper classes

### ISSUE THREAD

**Issue by davetapley** [fibo/trunx#33]
Since https://github.com/jgthms/bulma/releases/tag/0.9.3 we have e.g. `mx-auto`.

https://bulma.io/documentation/helpers/spacing-helpers/#list-of-all-spacing-helpers

**Comment by fibo** [comment]
Hi @davetapley thanks for reporting it

added here 341763d16a3d7868158973699814b8094d45479a

released as `v0.41.1`
