### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by davetapley** [fibo/trunx#35]
Might be as simple as updating this?

https://github.com/fibo/trunx/blob/d4b4c3c7044d5842f8957abfed2a4884043e7995/package.json#L62-L63

**Comment by fibo** [comment]
hi @davetapley ,

there is a new version `v0.42.0` on npm with updated dependencies. It should work with React 18.

I recently upgraded a project to React 18, it went smooth except I needed to add more types related to children prop.
