### ISSUE TITLE
Navbar.Divider doesn't exist

### ISSUE THREAD

**Issue by steph4nc** [fibo/trunx#8]
Looking at the Navbar docs, there is mention of Navbar.Divider, but when I try to use it I only get exceptions. I see the Navbar source file doesn't contain any mention for Divider. 

Docs: http://g14n.info/trunx/?selectedKind=Components&selectedStory=Navbar
Code: https://github.com/fibo/trunx/blob/master/src/component/Navbar.tsx

**Comment by fibo** [comment]
Hi, thank you for reporting it! (by the way, I was in CapeTown last january and it is really nice :)

I added the divider, it is available in version 0.10.1 just published now on the npm registry.

I also updated the story you linked with a basic navbar example.
