### ISSUE TITLE
React form library integration

### ISSUE THREAD

**Issue by steph4nc** [fibo/trunx#9]
It would be great if we could have integration with some react form library. 

There are many options, the biggest one is probably Formik, but I really like react-formal. With all these libraries it usually takes a bit of manual coding to integrate it into the stylesheet/template library or having to set everywhere what component to use to override the defaults. react-formal integrates nicely with react-widgets, which uses a custom bootstrap theme, so having bulma for that would be super awesome as well.

Thanks for making trunx, it is by far the react bulma library I prefer the most.

**Comment by ashnur** [comment]
I think that a form generator library could include trunx, but trunx shouldn't include any kind of UI generator (or form library), because it would limit the scope and add issues and problems from lots of different domains that in my opinion a library like trunx probably should try to solve. :)

**Comment by steph4nc** [comment]
Yeah, would be best to have separate extension libraries using trunx for different react libraries, like form libraries.

**Comment by ashnur** [comment]
Github  is having issues :)

**Comment by ashnur** [comment]
I leave this here as a possible option for later reference https://jsonforms.io/

**Comment by steph4nc** [comment]
I had an idea, don't know how viable it is, but it would be great if there was a way to get the list of classNames for a trunx component, so rather than using the component directly, I want all the classes that go with that component. Classes that are added via props, I think will be more difficult to resolve.

This would allow integration for things where you are limited to only inputting classNames to override the default styling.

**Comment by fibo** [comment]
Yes, we just need a naming convention for classname, for example

    trunx-Button

Where Button is the component class (constructor) name

**Comment by steph4nc** [comment]
> Yes, we just need a naming convention for classname, for example
> 
> ```
> trunx-Button
> ```
> Where Button is the component class (constructor) name

Wouldn't the default Bulma classnames be fine?

**Comment by fibo** [comment]
I mean if you need an additional CSS class to style the component.

Probably what you need is already available. Let me try with this answer, maybe is what you are looking for.

In the *getting started* section in g14n.info/trunx there are instructions to customize the build. For example I tryed with *materia* theme from https://github.com/jenil/bulmaswatch , for instance, https://github.com/jenil/bulmaswatch/blob/gh-pages/materia/_overrides.scss and I got a customized bulma similar to material design.

Does this fit your need? If yes, probably I need to improve documentation to make it more clear.

**Comment by steph4nc** [comment]
Oh no sorry, what I meant was a little bit different. What I was wondering, is if there is a way to do something like `Button.classes` and then you get all the classnames part of that button. But there is probably a way better way for solving these kind of things in React without exposing the classes.

**Comment by fibo** [comment]
My opinion is that in general, class names should be encapsulated.
